### PR TITLE
Gt/add support multi count

### PR DESCRIPTION
**Pull request by film42**
Now we can report message count on publish. Also fixes a typo in the specs. 😁 

cc @mmmries

### CODE REVIEW

**Comment by film42** [comment]
```
Harness::ActivePublisher
  has a version number
  async_queue_size.active_publisher
    updates the queue size count
  message_dropped.active_publisher
    increments the message was dropped counter
  message_published.active_publisher
    increments the message was dropped counter
    increments the message was dropped counter by the number provided
    records the publish latency
  wait_for_async_queue.active_publisher
    increments the message was dropped counter

Finished in 0.21601 seconds (files took 0.19574 seconds to load)
7 examples, 0 failures
```

**Review by mmmries — APPROVED** [review]
:shipit:

**Comment by mmmries** [comment]
~~Should we listen for `message_batch_published` to record latency? It looks like this just updated our listening of `message_published`, but in `active_publisher` you have a separate name for `message_batch_published`?~~

Chatted offline and `message_batch_published` is going away in favor of using a single instrument name

**Comment by film42** [comment]
Actually, that's a typo in active_publisher. Pushing a fix there now.

**Pull request merged**
